// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"palWindow","status":true,"description":"","parameters":{}},
{"name":"palScene","status":true,"description":"重写标题场景，仅保留新游戏与继续游戏选项。","parameters":{}},
{"name":"IsometricView","status":true,"description":"v1.0.2 等距投影插件 - 将RMMZ默认正交投影修改为斜45度投影","parameters":{"transformA":"1","transformB":"-1","transformC":"320.00","transformD":"0.5","transformE":"0.5","transformF":"0"}},
{"name":"DynamicTileLayers","status":true,"description":"High-layer tiles as Sprites for correct Isometric Occlusion z-sorting.","parameters":{"showDebug":"false"}},
{"name":"palStatus","status":true,"description":"[v1.0] 仿仙剑98柔情版状态界面","parameters":{}},
{"name":"Pal_Icon48","status":true,"description":"Paladin 48x48 Icon Support","parameters":{"IconSetFilename":"IconSet48","IconSize":"48"}},
{"name":"palItemList","status":true,"description":"Chinese Paladin Item List UI","parameters":{}},
{"name":"palMagic","status":true,"description":"Chinese Paladin Magic List UI","parameters":{}},
{"name":"palBattle","status":true,"description":"[v1.0] Chinese Paladin 98 Battle System & UI","parameters":{}},
{"name":"PAL98_Dialogue","status":true,"description":"[v2.0] 仙剑98柔情版 文字对话样式 | PAL98 Classic Dialogue System","parameters":{"FontSize":"48","LineHeight":"54","TitleColor":"#38c0a8","BodyColor":"#ffffff","ShadowOffsetX":"2","ShadowOffsetY":"2","FaceScale":"3","DialogueRegionHeight":"180","TopFaceX":"-66","TopFaceY":"-66","BottomFaceX":"-66","BottomFaceY":"-66","TopTextX":"-132","TopTextY":"0","BottomTextX":"0","BottomTextY":"66"}},
{"name":"palShop","status":true,"description":"Chinese Paladin Shop UI","parameters":{}}
];
